---
title: "STAT 184 Final Project"
Authors: Kaitlyn Klumb, Xinyi Bao, Samuel Quinn
output:
  html_document:
  df_print: paged
  pdf_document: default
  html_notebook: default
date: "`r Sys.Date()`"
---

***Background Information:***   
This dataset offers a perfect avenue to analyze and gain valuable insights from the luminaries of the platform, including comprehensive details on top creators' subscriber counts, video views, upload frequency, country of origin, earnings, and more.   

The primary dataset come from [here](https://www.kaggle.com/datasets/nelgiriyewithana/global-youtube-statistics-2023)

***Data Access:***
```{r}
# Loading primary data
GlobalYouTube <- read.csv("https://raw.githubusercontent.com/Cassiebxy/STAT-184-Final-Project/main/Global%20YouTube%20Statistics.csv")

library(ggplot2)
library(DataComputing)
library(tidyverse)
library(esquisse)
library(mosaic)

# Secondary Data
library(Lock5Data)

head(GlobalYouTube)
head(GlobalInternet2019)
```

***Data Wrangling:***
# Wrangling, E
data("GlobalInternet2019")
GlobalInternet2019$InternetSpeed1 <- round(GlobalInternet2019$InternetSpeed)
GlobalInternet2019 <- 
  GlobalInternet2019 %>%
  select(Country, InternetSpeed1, HoursOnline) %>%
  rename(InternetSpeed = InternetSpeed1)
GlobalInternet2019

# Wrangling, C
narrow_table <-
  GlobalYouTube %>%
  #mutate(popularity = video.views + subscribers) %>%
  pivot_longer(
    cols = c(`subscribers`, `video.views`),  #names of columns we want to become a new variable 
    names_to = "popularity.category",         #what you want to call the new column of the data in the line above
    values_to = "popularity"    #what you want to call the variable that stores the values
  )
narrow_table

***Linear Regression:***

***Data Visualization:***
# Visualizations, A
mWorldMap(GlobalInternet2019, key="Country", fill="InternetSpeed")
